export * from './admin/collections/admin';
export * from './auth/collections/auth';
export * from './files/collections/files';
export * from './folders/collections/folders';
export * from './health/collections/health';
export * from './storage/collections/storage';
export * from './trash/collections/trash';
export * from './dashboard/collections/dashboard';
export * from './status/collections/status';