# Generated by Django 6.0.6 on 2026-07-06 01:05

import core.validators.common.folder_name_validator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('unique_name', models.CharField(max_length=255, unique=True, verbose_name='Уникальное имя на диске')),
                ('size', models.IntegerField(verbose_name='Размер (байты)')),
                ('file_type', models.CharField(max_length=50, verbose_name='Тип файла')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('last_download_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего скачивания')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Количество скачиваний')),
                ('special_link', models.CharField(max_length=255, unique=True, verbose_name='Специальная ссылка')),
                ('is_public', models.BooleanField(default=False, verbose_name='Доступен по ссылке')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='previews/', verbose_name='Превью')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('action', models.CharField(choices=[('view', 'Просмотр'), ('download', 'Скачивание'), ('share_open', 'Открытие по ссылке')], max_length=20, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_app.file', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[core.validators.common.folder_name_validator.validate_folder_name], verbose_name='Название папки')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание папки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_app.folder', verbose_name='Родительская папка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'unique_together': {('user', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='Имя поля')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Новое значение')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время изменения')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_app.file', verbose_name='Файл')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_app.folder', verbose_name='Папка')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files_app.folder', verbose_name='Папка'),
        ),
        migrations.CreateModel(
            name='GuestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100, verbose_name='Имя гостя')),
                ('guest_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email гостя')),
                ('content', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_app.file', verbose_name='Файл')),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('view', 'Просмотр'), ('download', 'Скачивание')], max_length=10, verbose_name='Тип ссылки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='Разрешить комментарии')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Разрешённые пользователи')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files_app.file', verbose_name='Файл')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='tags',
            field=models.ManyToManyField(blank=True, to='files_app.tag', verbose_name='Теги'),
        ),
    ]
