# Generated by Django 6.0.6 on 2026-07-06 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
