# Generated by Django 6.0.6 on 2026-07-28 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0002_sharelink_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_app.folder', verbose_name='Папка'),
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files_app.file', verbose_name='Файл'),
        ),
    ]
