# Generated by Django 6.0.6 on 2026-07-28 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0003_sharelink_folder_alter_sharelink_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Коллекция', max_length=255, verbose_name='Название коллекции')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата истечения')),
                ('allow_comments', models.BooleanField(default=False, verbose_name='Разрешить комментарии')),
                ('allow_download', models.BooleanField(default=True, verbose_name='Разрешить скачивание')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль (хеш)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
        ),
    ]
