# Generated by Django 6.0.6 on 2026-07-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0004_sharedcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль (хеш)'),
        ),
    ]
