# Generated by Django 6.0.6 on 2026-07-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0005_sharelink_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='password_download',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль для скачивания (хеш)'),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='password_view',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль для просмотра (хеш)'),
        ),
    ]
