# Generated by Django 6.0.6 on 2026-08-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0006_sharelink_password_download_sharelink_password_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcollection',
            name='password_download',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль для скачивания (хеш)'),
        ),
        migrations.AddField(
            model_name='sharedcollection',
            name='password_view',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль для просмотра (хеш)'),
        ),
    ]
