# Generated by Django 6.0.6 on 2026-08-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0007_sharedcollection_password_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcollection',
            name='files',
            field=models.ManyToManyField(blank=True, to='files_app.file', verbose_name='Файлы в коллекции'),
        ),
        migrations.AddField(
            model_name='sharedcollection',
            name='folders',
            field=models.ManyToManyField(blank=True, to='files_app.folder', verbose_name='Папки в коллекции'),
        ),
    ]
